# making more diversity
DEFAULT_NAME = ['items','entities', 'things','elements']
DEFAULT_COMMAND = ['find','select','choose','locate']
COMMON_USE_DICT = ["material","color","placement","shape"]
BEGIN_STATE = ["Look carefully at the room, ", "Take a close look at the room, ","Inspect every corner of the room, ","Survey the room meticulously, ","Examine the room thoroughly, "]

size_ratio = 0.35
anchor_OR_sample = 5

REFERING_TYPES = [
    "fine grained category",
    "coarse grained category",
    "color",
    "texture",
    "material",
    "weight",
    "size",
    "shape",
    "placement",
    "state",
    "function",
    "other features"
]
# some aborted objects class
EXCLUDED_OBJECTS = ["wall", "ceiling", "floor","person"]
SPACE_TYPES = [
    "size",
    "shape",
    "placement"
]
wrong_ = ['scene0409_00__0_cooking region', 'scene0092_03__0_study region', 'scene0118_02__0_living region', 'scene0055_01__0_resting region', '1mp3d_0059_region17__0_corridor region', '1mp3d_0002_region18__0_corridor region', 'scene0010_01__0_study region', '1mp3d_0013_region9__0_corridor region', '1mp3d_0013_region33__0_toliet region', 'scene0035_01__0_resting region', '1mp3d_0037_region30__1_toliet region', '1mp3d_0054_region9__0_corridor region', 'scene0001_00__0_living region', '3rscan1240__0_storage region', '3rscan0763__0_study region', 'scene0310_01__0_cooking region', '1mp3d_0017_region20__0_corridor region', '3rscan0307__0_living region', 'scene0151_00__0_living region', '1mp3d_0004_region22__0_study region', 'scene0236_00__0_resting region', '3rscan0920__0_living region', 'scene0099_01__0_dinning region', 'scene0051_01__0_resting region', '1mp3d_0037_region6__1_toliet region', '3rscan1033__0_living region', '3rscan0862__0_living region', '3rscan0781__0_living region', '1mp3d_0044_region4__0_toliet region', '1mp3d_0008_region1__0_living region', 'scene0680_00__0_study region', 'scene0381_00__0_living region', '1mp3d_0012_region10__0_corridor region']

Common_Descripition = dict()

Common_Descripition['coarse grained category'] = [
    'Furniture',
    'Sleep/Rest appliance',
    'Decorations',
    'Store and organize supplies',
    'Study and office supplies',
    'Cleaning supplies',
    'Kitchenware and dining utensil',
    'Sanitary ware products',
    'Lighting fixtures',
    'Entertainment and leisure equipment',
    'Electronic products',
    'Personal effects'
]
Common_Descripition['color'] = [
    'Red',
    'Orange',
    'Yellow',
    'Green',
    'Blue',
    'Purple',
    'Black',
    'White',
    'Gray',
    'Brown',
    'Pink',
    'Silver', 
    'Gold',
    'Transparent', 
    'More than one color'
]

Common_Descripition['material'] = [
    'Wood/Paper',
    'Metal',
    'Plastic',
    'Glass',
    'Fabric/Feather',
    'Leather',
    'Ceramic',
    'Concrete/Stone',
]
Common_Descripition['shape'] = [
    'Rectangular',
    'Circular',
    'Cylindrical',
    'Spherical',
    'Triangular',
    'Cuboid',
    'Irregular',
    'Conical'
]
Common_Descripition['weight'] = [
    'Heavy',
    'Medium',
    'Light'
]
Common_Descripition['size'] = [
    'Large',
    'Medium',
    'Small'
]
Common_Descripition['placement'] = [
    'Standing upright', 'Piled up', 'Leaning', 'Lying flat', 'Hanging'
]

object_template = {
    "Space":[ 
              # with class
              ["Adorned with {other_features}, the {fine_grained_category} is {placement} and is {size} in size. ","the {fine_grained_category}"],
              ["While {placement}, the {fine_grained_category} has a {shape} appearance.", "the {fine_grained_category}"],
              
              ["This {shape} {fine_grained_category} has a {placement} placement, and it has {other_features}. ","This {shape} {fine_grained_category}"],
              # without class 
              ["This entity is {placement} and has a {shape} shape, designed for {function}. ", "This entity"],
              ["Belongs to {coarse_grained_category}, the {shape} shape {size} size item is {placement}. ","the {shape} shape {size} size item"],
              ["Combining style with functionality, the {color} item with a {texture} is {placement} and {size} in size. ", "the {color} item with a {texture}"],
              ["Idealy for {function}, the object is {placement} and {shape} in shape. ","the object"]
             ],
    "Attribute":[
            ["In a {color} color, the {fine_grained_category} is ready to elevate any {function}. ","the {fine_grained_category}"],
            ["Belonging to the {coarse_grained_category}, the {color} {fine_grained_category} is made of {material}. ","the {color} {fine_grained_category}"],
            ["This object is designed for {function}, with a focus on {material} material and {shape} quality. ", "This object"],
            ["The {texture} {fine_grained_category}, with its {shape} shape, is a {color} {material} masterpiece, {placement} and {size}, ideal for {function}. ","The {texture} {fine_grained_category}"],
            ["The {fine_grained_category}, {placement}, is a blend of {material}, {texture}, and {shape} shape, perfect for {function}. ", "The {fine_grained_category}"],
            ["Belonging to {coarse_grained_category}, the {color} item is {size} in size and play a role in {function}, with {other_features} ","the {color} item"],
            ["The {color} item is belonging to {coarse_grained_category}, with {other_features}", "The {color} item"]
        ],
    "Region-role":[
        #with class
        ["With {color} color and {shape} shape, the {fine_grained_category} has its special role: {region_role} ", "the {fine_grained_category}"],
        ["The {fine_grained_category} plays an important role while {placement}, because {region_role}. ","The {fine_grained_category}"],
        ["This {state} {material} entity distinguish oneself, {region_role}","This {state} {material} entity"],
        ["Belonging to {coarse_grained_category}, this object is special in the room while {region_role}. ","this object"],
    ]
}

all_translate = {
    "adhesive tape": "胶带",
    "air conditioner": "空调",
    "alarm": "报警器",
    "album": "相册/唱片集",
    "arch": "拱门",
    "backpack": "背包",
    "bag": "包",
    "balcony": "阳台",
    "ball": "球",
    "banister": "楼梯扶手",
    "bar": "酒吧",
    "barricade": "障碍物",
    "baseboard": "踢脚线",
    "basin": "盆地",
    "basket": "篮子",
    "bathtub": "浴缸",
    "beam": "梁",
    "beanbag": "懒人沙发",
    "bed": "床",
    "bench": "长凳",
    "bicycle": "自行车",
    "bidet": "坐浴盆",
    "bin": "垃圾桶",
    "blackboard": "黑板",
    "blanket": "毯子",
    "blinds": "百叶窗",
    "board": "板",
    "body loofah": "身体搓澡巾",
    "book": "书",
    "boots": "靴子",
    "bottle": "瓶子",
    "bowl": "碗",
    "box": "盒子",
    "bread": "面包",
    "broom": "扫帚",
    "brush": "刷子",
    "bucket": "桶",
    "cabinet": "橱柜",
    "calendar": "日历",
    "camera": "相机",
    "can": "罐头",
    "candle": "蜡烛",
    "candlestick": "烛台",
    "cap": "帽子",
    "car": "汽车",
    "carpet": "地毯",
    "cart": "手推车",
    "case": "箱子",
    "ceiling": "天花板",
    "chair": "椅子",
    "chandelier": "吊灯",
    "cleanser": "清洁剂",
    "clock": "钟",
    "clothes": "衣服",
    "clothes dryer": "干衣机",
    "coat hanger": "衣架",
    "coffee maker": "咖啡机",
    "coil": "线圈",
    "column": "柱子",
    "commode": "便桶",
    "computer": "电脑",
    "conducting wire": "导线",
    "container": "容器",
    "control": "控制",
    "copier": "复印机",
    "cosmetics": "化妆品",
    "couch": "沙发",
    "counter": "柜台",
    "countertop": "台面",
    "crate": "大箱子",
    "crib": "婴儿床",
    "cube": "立方体",
    "cup": "杯子",
    "curtain": "窗帘",
    "cushion": "垫子",
    "decoration": "装饰品",
    "desk": "书桌",
    "detergent": "洗涤剂",
    "device": "设备",
    "dish rack": "碗架",
    "dishwasher": "洗碗机",
    "dispenser": "分配器",
    "divider": "分隔物",
    "door": "门",
    "door knob": "门把手",
    "doorframe": "门框",
    "doorway": "门口",
    "drawer": "抽屉",
    "dress": "连衣裙",
    "dresser": "梳妆台",
    "drum": "鼓",
    "duct": "管道",
    "dumbbell": "哑铃",
    "dustpan": "簸箕",
    "dvd": "DVD",
    "eraser": "橡皮",
    "excercise equipment": "健身器材",
    "fan": "风扇",
    "faucet": "水龙头",
    "fence": "围栏",
    "file": "文件",
    "fire extinguisher": "灭火器",
    "fireplace": "壁炉",
    "floor": "地板",
    "flowerpot": "花盆",
    "flush": "冲洗",
    "folder": "文件夹",
    "food": "食物",
    "footstool": "脚踏凳",
    "frame": "框架",
    "fruit": "水果",
    "furniture": "家具",
    "garage door": "车库门",
    "garbage": "垃圾",
    "glass": "玻璃",
    "globe": "地球仪",
    "glove": "手套",
    "grab bar": "扶手",
    "grass": "草",
    "guitar": "吉他",
    "hair dryer": "吹风机",
    "hamper": "篮子",
    "handle": "把手",
    "hanger": "衣架",
    "hat": "帽子",
    "headboard": "床头板",
    "headphones": "耳机",
    "heater": "加热器",
    "helmets": "头盔",
    "holder": "支架",
    "hook": "钩子",
    "humidifier": "加湿器",
    "ironware": "铁器",
    "jacket": "夹克",
    "jalousie": "百叶窗",
    "jar": "罐子",
    "kettle": "水壶",
    "keyboard": "键盘",
    "kitchen island": "厨房岛台",
    "kitchenware": "厨具",
    "knife": "刀",
    "label": "标签",
    "ladder": "梯子",
    "lamp": "灯",
    "laptop": "笔记本电脑",
    "ledge": "岩架",
    "letter": "信",
    "light": "灯",
    "luggage": "行李",
    "machine": "机器",
    "magazine": "杂志",
    "mailbox": "邮箱",
    "map": "地图",
    "mask": "面具",
    "mat": "垫子",
    "mattress": "床垫",
    "menu": "菜单",
    "microwave": "微波炉",
    "mirror": "镜子",
    "molding": "造型",
    "monitor": "监视器",
    "mop": "拖把",
    "mouse": "鼠标",
    "napkins": "餐巾纸",
    "notebook": "笔记本",
    "object": "物体",
    "ottoman": "脚凳",
    "oven": "烤箱",
    "pack": "包装",
    "package": "包裹",
    "pad": "垫",
    "pan": "平底锅",
    "panel": "面板",
    "paper": "纸",
    "paper cutter": "裁纸刀",
    "partition": "隔断",
    "pedestal": "底座",
    "pen": "笔",
    "person": "人",
    "piano": "钢琴",
    "picture": "图片",
    "pillar": "柱子",
    "pillow": "枕头",
    "pipe": "管道",
    "pitcher": "投手",
    "plant": "植物",
    "plate": "盘子",
    "player": "播放器",
    "plug": "插头",
    "plunger": "疏通器",
    "pool": "池",
    "pool table": "台球桌",
    "poster": "海报",
    "pot": "锅",
    "price tag": "价格标签",
    "printer": "打印机",
    "projector": "投影仪",
    "purse": "钱包",
    "rack": "架子",
    "radiator": "散热器",
    "radio": "收音机",
    "rail": "轨道",
    "range hood": "抽油烟机",
    "refrigerator": "冰箱",
    "remote control": "遥控器",
    "ridge": "山脊",
    "rod": "杆",
    "roll": "卷",
    "roof": "屋顶",
    "rope": "绳子",
    "sack": "麻袋",
    "salt": "盐",
    "scale": "秤",
    "scissors": "剪刀",
    "screen": "屏幕",
    "seasoning": "调料",
    "shampoo": "洗发水",
    "sheet": "床单",
    "shelf": "架子",
    "shirt": "衬衫",
    "shoe": "鞋",
    "shovel": "铲子",
    "shower": "淋浴",
    "sign": "标志",
    "sink": "水槽",
    "soap": "肥皂",
    "soap dish": "肥皂盒",
    "soap dispenser": "肥皂分配器",
    "socket": "插座",
    "speaker": "扬声器",
    "sponge": "海绵",
    "spoon": "勺子",
    "stairs": "楼梯",
    "stall": "隔间",
    "stand": "站立",
    "stapler": "订书机",
    "statue": "雕像",
    "step": "步骤",
    "stick": "棍",
    "stool": "凳子",
    "stopcock": "截止阀",
    "stove": "炉子",
    "structure": "结构",
    "sunglasses": "太阳镜",
    "support": "支持",
    "switch": "开关",
    "table": "桌子",
    "tablet": "平板电脑",
    "teapot": "茶壶",
    "telephone": "电话",
    "thermostat": "恒温器",
    "tissue": "纸巾",
    "tissue box": "纸巾盒",
    "toaster": "烤面包机",
    "toilet": "厕所",
    "toilet paper": "卫生纸",
    "toiletry": "梳洗用品",
    "tool": "工具",
    "toothbrush": "牙刷",
    "toothpaste": "牙膏",
    "towel": "毛巾",
    "toy": "玩具",
    "tray": "托盘",
    "treadmill": "跑步机",
    "trophy": "奖杯",
    "tube": "管",
    "tv": "电视",
    "umbrella": "伞",
    "urn": "瓮",
    "utensil": "用具",
    "vacuum cleaner": "吸尘器",
    "vanity": "虚荣",
    "vase": "花瓶",
    "vent": "通风口",
    "ventilation": "通风",
    "wall": "墙",
    "wardrobe": "衣柜",
    "washbasin": "洗手盆",
    "washing machine": "洗衣机",
    "water cooler": "饮水机",
    "water heater": "热水器",
    "window": "窗户",
    "window frame": "窗框",
    "windowsill": "窗台",
    "wine": "葡萄酒",
    "wire": "电线",
    "wood": "木头",
    "wrap": "包装纸"
}
PLURAL_DICT= {"cabinet": "cabinets", "chair": "chairs", "sink": "sinks", "door": "doors", "microwave": "microwaves", "dishwasher": "dishwashers", "window": "windows", "bin": "bins", "jacket": "jackets", "doorframe": "doorframes", "couch": "couches", "counter": "counters", "refrigerator": "refrigerators", "table": "tables", "teapot": "teapots", "switch": "switches", "box": "boxes", "object": "objects", "socket": "sockets", "bottle": "bottles", "mirror": "mirrors", "stairs": "stairs", "stand": "stands", "tv": "tvs", "bench": "benches", "shelf": "shelves", "plant": "plants", "clothes": "clothes", "pillow": "pillows", "blanket": "blankets", "bag": "bags", "rack": "racks", "vacuum cleaner": "vacuum cleaners", "toilet": "toilets", "soap dispenser": "soap dispensers", "stall": "stalls", "grab bar": "grab bars", "dispenser": "dispensers", "molding": "moldings", "bed": "beds", "light": "lights", "picture": "pictures", "dresser": "dressers", "desk": "desks", "windowsill": "windowsills", "decoration": "decorations", "curtain": "curtains", "rail": "rails", "window frame": "window frames", "clothes dryer": "clothes dryers", "heater": "heaters", "commode": "commodes", "basket": "baskets", "shoe": "shoes", "mat": "mats", "towel": "towels", "tissue box": "tissue boxes", "toilet paper": "toilet papers", "blackboard": "blackboards", "drawer": "drawers", "stool": "stools", "sign": "signs", "purse": "purses", "ledge": "ledges", "lamp": "lamps", "cart": "carts", "clock": "clocks", "coat hanger": "coat hangers", "hat": "hats", "bathtub": "bathtubs", "washbasin": "washbasins", "monitor": "monitors", "board": "boards", "computer": "computers", "divider": "dividers", "keyboard": "keyboards", "paper": "papers", "cup": "cups", "mouse": "mice", "fire extinguisher": "fire extinguishers", "flowerpot": "flowerpots", "frame": "frames", "machine": "machines", "printer": "printers", "tray": "trays", "copier": "copiers", "furniture": "furniture", "fireplace": "fireplaces", "bucket": "buckets", "stove": "stoves", "oven": "ovens", "countertop": "countertops", "bowl": "bowls", "alarm": "alarms", "radiator": "radiators", "remote control": "remote controls", "washing machine": "washing machines", "dish rack": "dish racks", "tissue": "tissues", "bicycle": "bicycles", "hamper": "hampers", "case": "cases", "guitar": "guitars", "backpack": "backpacks", "speaker": "speakers", "dumbbell": "dumbbells", "pipe": "pipes", "crate": "crates", "book": "books", "kettle": "kettles", "kitchenware": "kitchenwares", "pack": "packs", "jar": "jars", "water cooler": "water coolers", "coffee maker": "coffee makers", "stopcock": "stopcocks", "paper cutter": "paper cutters", "container": "containers", "folder": "folders", "fan": "fans", "vase": "vases", "telephone": "telephones", "toy": "toys", "faucet": "faucets", "garage door": "garage doors", "ladder": "ladders", "wood": "woods", "rod": "rods", "ottoman": "ottomans", "person": "people", "car": "cars", "bar": "bars", "soap dish": "soap dishes", "projector": "projectors", "vanity": "vanities", "vent": "vents", "pot": "pots", "carpet": "carpets", "structure": "structures", "blinds": "blinds", "bidet": "bidets", "grass": "grasses", "letter": "letters", "wardrobe": "wardrobes", "magazine": "magazines", "plunger": "plungers", "shower": "showers", "device": "devices", "can": "cans", "basin": "basins", "pan": "pans", "cushion": "cushions", "label": "labels", "brush": "brushes", "laptop": "laptops", "kitchen island": "kitchen islands", "seasoning": "seasonings", "soap": "soaps", "headboard": "headboards", "plate": "plates", "scale": "scales", "dress": "dresses", "hanger": "hangers", "statue": "statues", "glass": "glasses", "range hood": "range hoods", "sack": "sacks", "toaster": "toasters", "broom": "brooms", "detergent": "detergents", "rope": "ropes", "mattress": "mattresses", "chandelier": "chandeliers", "helmets": "helmets", "calendar": "calendars", "sheet": "sheets", "barricade": "barricades", "doorway": "doorways", "footstool": "footstools", "ball": "balls", "hair dryer": "hair dryers", "toiletry": "toiletries", "eraser": "erasers", "drum": "drums", "piano": "pianos", "spoon": "spoons", "shovel": "shovels", "umbrella": "umbrellas", "body loofah": "body loofahs", "door knob": "door knobs", "screen": "screens", "step": "steps", "balcony": "balconies", "pen": "pens", "shirt": "shirts", "mask": "masks", "humidifier": "humidifiers", "notebook": "notebooks", "knife": "knives", "garbage": "garbage", "plug": "plugs", "holder": "holders", "headphones": "headphones", "mop": "mops", "banister": "banisters", "fence": "fences", "menu": "menus", "candle": "candles", "roll": "rolls", "beanbag": "beanbags", "utensil": "utensils", "pool table": "pool tables", "duct": "ducts", "pool": "pools", "coil": "coils", "air conditioner": "air conditioners", "crib": "cribs", "price tag": "price tags", "luggage": "luggage", "cleanser": "cleansers", "conducting wire": "conducting wires", "glove": "gloves", "sponge": "sponges", "fruit": "fruits", "tube": "tubes", "jalousie": "jalousies", "radio": "radios", "player": "players", "dustpan": "dustpans", "food": "foods", "flush": "flushes", "toothbrush": "toothbrushes", "toothpaste": "toothpastes", "water heater": "water heaters", "pad": "pads", "ventilation": "ventilations", "stick": "sticks", "wrap": "wraps", "ironware": "ironwares", "excercise equipment": "excercise equipments", "adhesive tape": "adhesive tapes", "pitcher": "pitchers", "cosmetics": "cosmetics", "sunglasses": "sunglasses", "treadmill": "treadmills", "panel": "panels", "globe": "globes", "file": "files", "candlestick": "candlesticks", "partition": "partitions", "thermostat": "thermostats", "tool": "tools", "poster": "posters", "bread": "breads", "support": "supports", "cube": "cubes", "handle": "handles", "tablet": "tablets", "wire": "wires", "napkins": "napkins", "shampoo": "shampoos", "package": "packages", "dvd": "dvds", "trophy": "trophies", "mailbox": "mailboxes", "hook": "hooks", "stapler": "staplers", "pedestal": "pedestals", "map": "maps", "baseboard": "baseboards", "album": "albums", "control": "controls", "camera": "cameras", "wine": "wines", "salt": "salts", "cap": "caps", "urn": "urns", "boots": "boots", "scissors": "scissors","pillar":"pillars", "column":"columns", "roof":"roves", "ridge":"ridges", "arch":"arches", "beam":"beams"}
function_base_category = {
"storage and organization supplies": ['crate', 'drawer', 'wardrobe', 'rack', 'bin', 'cabinet', 'shelf',  'container', 'box', 'dresser', 'hamper', 'basket', 'luggage',"backpack","bag","bucket","case","coat hanger","commode","pack","dish rack",'mailbox',"sack","purse"],
"electronic products":['refrigerator', 'hair dryer', 'laptop', 'microwave', 'water cooler', 'dishwasher', 'tv', 'fan', 'printer', 'humidifier', 'copier', 'air conditioner', 'washing machine', 'camera', 'remote control', 'tablet', 'speaker', 'keyboard', 'monitor', 'telephone', 'radio', 'player', 'coffee maker', 'projector', 'computer',"clothes dryer","heater","headphones","machine","mouse","oven","radiator","thermostat","toaster","treadmill","vacuum cleaner","water heater"],
'lighting fixtures':['light', 'lamp','chandelier',"candle"],
"personal clothings":['dress', 'glove', 'shoe', 'clothes', 'boots', 'shirt', 'mask', 'hat',  'jacket'],
"kitchenware and dining utensil": ['knife', 'spoon', 'kitchenware', 'tray', 'pitcher', 'plate',  'bowl', 'pot', 'pan', 'teapot', 'coffee maker', 'jar', 'toaster', 'kettle',"microwave","oven","range hood","stove"],
"information media":['player', 'dvd', 'file', 'panel', 'magazine', 'blackboard', 'album', 'menu', 'sign', 'picture', 'poster', 'notebook', 'book', 'camera', 'calendar', 'computer', 'map', 'paper', 'monitor', 'radio', 'screen',"alarm","clock","label","laptop","monitor","letter","price tag","tablet","telephone","tv","headphones","speaker","globe"],
"bath tools":['sink', 'shower', 'washbasin', 'soap dispenser', 'bathtub', 'faucet',  'bidet', 'toilet','body loofah',"flush","hair dryer", "shampoo","soap","toiletry","toothbrush","toothpaste"],
"basic components and accessories of the building":['baseboard', 'door', 'switch', 'duct', 'windowsill', 'partition', 'blinds', 'window',  'door knob', 'window frame', 'banister', 'ledge', 'vent', 'structure',  'support', 'socket',  'panel', 'doorframe', 'frame',"balcony","arch","ceiling","column","doorway","fence","floor","garage door","grab bar","jalousie","pipe","pillar","rail","pool","ridge","roof","stairs","stall","step","ventilation","wall","column", "arch", "beam"]
}

object_have_state = ['cabinet', 'plate', 'door', 'light', 'window', 'tv', 'socket', 'stove', 'lamp', 'backpack', 'case', 'shelf', 'vase', 'wardrobe', 'purse', 'bin', 'refrigerator', 'book', 'container', 'switch', 'box', 'bucket', 'sack', 'bag', 'range hood', 'toilet', 'piano', 'printer', 'laptop', 'bathtub', 'monitor', 'basket', 'flowerpot', 'microwave', 'computer', 'air conditioner', 'package', 'washing machine', 'clothes dryer', 'umbrella', 'notebook', 'tablet', 'jar', 'faucet', 'oven', 'bowl', 'dishwasher', 'screen', 'drawer', 'crate', 'dish rack', 'magazine', 'treadmill', 'copier', 'toaster', 'file', 'pot', 'pack', 'hair dryer', 'radio', 'hamper', 'garage door', 'jalousie', 'bidet', 'projector', 'mailbox', 'humidifier', 'letter', 'can', 'player', 'pool']
